"""Add is_producer columns

Revision ID: 5e5c8ffd6a01
Revises: a37f5e2a05ec
Create Date: 2026-01-13 19:17:52.124220

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e5c8ffd6a01'
down_revision: Union[str, Sequence[str], None] = 'a37f5e2a05ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_producer', sa.Boolean(), nullable=False))
    op.create_unique_constraint(None, 'users', ['is_producer'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'is_producer')
    # ### end Alembic commands ###
